### ISSUE TITLE
`create_env` and message

### ISSUE THREAD

**Issue by c1au6i0** [luciorq/condathis#15]
Eveytime I run `create_env` even with `verbose = full`, i am expecting some sort of message that is confirming that everything went well. Something similar to running mircromamba in the terminal in which you get  that `transaction finished` message.  
Some sort of "env succesfully created` when things go smoothly. Not sure if it is feasible to add and if it is of help for users...

**Comment by luciorq** [comment]
Thank you for the suggestion:

Added better messaging for `verbose = "full"` and `verbose = "output"`.
Additionally added messages to `remove_env()`

<img width="688" alt="Screenshot 2024-11-08 at 06 06 24" src="https://github.com/user-attachments/assets/ff1703ae-1547-4163-8878-a94a68a9eb0f">
