### ISSUE TITLE
remove_env() message

### ISSUE THREAD

**Issue by c1au6i0** [luciorq/condathis#20]
It would be nice to have a message similar to `create_env` that indicates that the env has been removed.

**Comment by luciorq** [comment]
This message already exists but is not displayed when the argument verbose = "silent", which is currently the default setting.

What would be the expected behavior in this case?

Should we detect whether the session is interactive and display the message even if verbose = "silent"?

**Comment by luciorq** [comment]
Relevant code block:

https://github.com/luciorq/condathis/blob/ec3bf42c9d3b6dc8e04a25c51d5c2aa95ab25874/R/remove_env.R#L38-L44

**Comment by c1au6i0** [comment]
I see, no I think is perfectly  fine. My bad that I did not realize that.
