### ISSUE TITLE
 solution for STDOUT redirection

### ISSUE THREAD

**Issue by c1au6i0** [luciorq/condathis#5]
The function `condathis::run` does not allow redirection with `>`   : 

`condathis::run("echo", "pippo", ">", "pippo.txt", env_name = `my-env`)`

This could be implemented exposing the `stdout` argument of `processx::run`:

```
processx::run(
    command = "ls"
    , stdout = "file.txt"
)
```

WHY: some bioinformatics tools use `>`  to write files (i.e. `minimap2 align`, `samtools`...)

**Comment by luciorq** [comment]
Thank you for the suggestion!

It is now implemented as of version 0.0.3.9003 from commit: [a2fe539](https://github.com/luciorq/condathis/commit/a2fe539958e706968fd631797455167bf9f08878)
