### ISSUE TITLE
list_env() is listing environments inacessible by condathis

### ISSUE THREAD

**Issue by luciorq** [luciorq/condathis#6]
- Current behavior: environments manually created by the user are being listed together with the environments.

- Desired behavior: `condathis::env_list()` should list only environments that are managed by `condathis`.

**Comment by luciorq** [comment]
Fixed

**Comment by c1au6i0** [comment]
What happened to `env_list`? I was looking for it :)

**Comment by luciorq** [comment]
Just as a note in previous versions the function was called `list_env()` and was not exported, but it now stabilized as `condathis::list_envs()`.
